# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cqT__1SQj7O0fG5BsSY45FSqiWskWXBj
"""

# Naming element of the game
def askname():
    while True:
        player_name = input("The executioner invites you to provide your name: ")
        if player_name.isalpha():
            print("The executioner says: 'A fine name indeed,", player_name, ". Welcome, let's play hangman.'")
            return player_name
        else:
            print("The executioner says: '", player_name, "HA! That is a quite ridiculous name. Please try again with letters, for I hate spaces and numbers |:<'")


def guess_letter(guessed_letters, word_letters, wrong_guess, lives, execution_word):
    while True:
        letter = input("The word I'm thinking of is " + str(len(execution_word)) + " letters long. Which letter will you choose? ").lower()
        if len(letter) != 1:
            print("CHEATER! Only one letter at a time, be careful or I might dock one of your lives.")
        else:
            break

    if letter in guessed_letters:
        print("You have already guessed that letter, try again.")
    elif letter in word_letters:
        guessed_letters.append(letter)
        print("Hm, yes. I'll allow it. That letter is in the word, after all.")
    else:
        wrong_guess += 1
        print("AHA! A rookie error. That letter is not in the word. You have", lives - wrong_guess, "lives remaining.")

    return wrong_guess


def guess_word(execution_word, wrong_guess, lives):
    word = input("Enter your word: ").lower()

    if word == execution_word.lower():
        print("Congratulations! You chose wisely...the hangman was never hanged, and is a freeman once more.")
        return True, wrong_guess
    else:
        wrong_guess += 1
        print("no, no, no, no, NO! WRONG! Be careful, you only have", lives - wrong_guess, "lives remaining.")
        return False, wrong_guess


def play_game(player_name):
    execution_word = 'Python'
    word_letters = list(execution_word.lower())
    guessed_letters = []
    lives = 6
    wrong_guess = 0

    print("The executioner grins. 'Let us begin,", player_name, ".'")

    while wrong_guess < lives:
        show = []
        for letter in word_letters:
            if letter in guessed_letters:
                show.append(letter)
            else:
                show.append("_")

        print(" ".join(show))

        if "_" not in show:
            print("Congratulations! You chose wisely...the hangman was never hanged, and is a freeman once more.")
            break

        word_or_letter = input("Will you guess a word or a letter? ").lower()

        if word_or_letter == 'word':
            won, wrong_guess = guess_word(execution_word, wrong_guess, lives)
            if won:
                break
        elif word_or_letter == 'letter':
            wrong_guess = guess_letter(guessed_letters, word_letters, wrong_guess, lives, execution_word)
        else:
            print("The executioner stares at you. 'Word or letter, please.'")

    else:
        print("The executioner gives a crooked, toothy, grin. 'My bloodlust will finally be satisfied, you LOSe. Mwahaha...' \n",  player_name, "The word was", execution_word, ".'")


def main():
    player_name = askname()
    play_game(player_name)

main()