# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qpk5vYS30p_pCTTX3EGvGU_mVk9WhF2J
"""

# Naming element of the game
def askname():
    while True:
        player_name = input("The executioner invites you to provide your name: ")
        if player_name.isalpha():
            hangmanexperience = input("The executioner says: 'A fine name indeed, " + player_name + ". Have you ever played Hangman before?' (yes/no)").lower()
            if hangmanexperience == 'yes':
              print()
              return player_name
            elif hangmanexperience == 'no':
              print("'Hangman is quite a simple game. I, the executioner, am thinking of a word. You, the player, must guess it. \n I will give you 6 chances to do this before the condemned man is hanged.\n I will give you opportunities to guess, but for each incorrect guess, you will lose a life.'")
              return player_name
        else:
          print("The executioner says: '", player_name, "HA! That is a quite ridiculous name. Please try again with letters, for I hate spaces and numbers |:<'")


def guess_letter(guessed_letters, word_letters, wrong_guess, lives, execution_word):
    while True: #does not actually check whether something is true or false. Just loops until broken by valid guess (i.e. only 1 letter)
        print("Letters guessed so far: ", guessed_letters) #can't concatenate this one as guessed_letters is a list. Replaced + with ,
        print("Lives left: ", (lives-wrong_guess))
        letter = input("The word I'm thinking of is " + str(len(execution_word)) + " letters long. Which letter will you choose? ").lower() #following line does not work if len(execution_word) is not made into a string variable. Is it because otherwise the alias (letter) will be multiple variable types?
        if len(letter) != 1: #you can only guess 1 letter at a time
            print("CHEATER! Only one letter at a time, be careful or I might dock one of your lives.")
        else:
            break

    if letter in guessed_letters: #ensures that same letter isn't guessed twice
        print("You have already guessed that letter, try again.")
    elif letter in word_letters: #if it is a valid, correct guess. Then the letter will be added to the list of letters already guessed
        guessed_letters.append(letter)
        print("Hm, yes. I'll allow it. That letter is in the word, after all.")
    else: #if it is a valid incorrect guess, then a life will be deducted.
        wrong_guess += 1
        print("AHA! A rookie error. That letter is not in the word. You have", lives - wrong_guess, "lives remaining.")

    return wrong_guess #wrong guess is returned no matter if the letter guessed was right or wrong


def guess_word(execution_word, wrong_guess, lives):
    word = input("Enter your word: ").lower()

    if word == execution_word.lower():
        print("Congratulations! You chose wisely...the hangman was never hanged, and is a freeman once more.")
        return True, wrong_guess
    else:
        wrong_guess += 1
        print("no, no, no, no, NO! WRONG! Be careful, you only have", lives - wrong_guess, "lives remaining.")
        return False, wrong_guess


def play_game(player_name):
    execution_word = 'Python'
    word_letters = list(execution_word.lower()) #word is turned into the multiple letters which comprise it
    guessed_letters = []
    lives = 6
    wrong_guess = 0

    print("The executioner grins. 'Let us begin,", player_name, ".'")

    while wrong_guess < lives: #i.e. while play is ongoing
        show = [] #what gets displayed to the player('_ for unknowns, letter for correct guesses)
        for letter in word_letters:
            if letter in guessed_letters:
                show.append(letter)
            else:
                show.append("_")

        print(" ".join(show))

        if "_" not in show: #acts like a circuit breaker. When all letters guessed, there are no underscores. So they must win
            print("Congratulations! You chose wisely...the hangman was never hanged, and is a freeman once more.")
            play_again()
            break

        word_or_letter = input("Will you guess a word or a letter? ").lower()

        if word_or_letter == 'word':
            won, wrong_guess = guess_word(execution_word, wrong_guess, lives)
            if won:
                play_again()
                break
        elif word_or_letter == 'letter':
            wrong_guess = guess_letter(guessed_letters, word_letters, wrong_guess, lives, execution_word)
        else:
            print("The executioner stares at you. 'Word or letter, please.'")

    else:
        print("The executioner gives a crooked, toothy, grin. 'My bloodlust will finally be satisfied, you LOSe. Mwahaha...' \n",  player_name, "The word was", execution_word, ".'")
        play_again()

def play_again():
  while True:
    answer = input("Would you like to play again? (yes/no)").lower()
    if answer == 'yes':
      player_name = askname()
      play_game(player_name)
    elif answer == 'no':
      print("The executioner nods and waves their skinny, translucent hand 'Well played. Farewell'")
      break
    else:
      print("Do you really want to be stuck here forever? Yes or no, please.")

player_name = askname()
play_game(player_name)