# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AOTDhOdcfGZvGzr-2zBMWb1QT6oWcm92

Hangman — Game Logic
1. Intro / Name Entry

Display a welcome message introducing the game
Call askname() — prompts the user for their name

Only accepts alphabetical characters (no spaces or special characters)
On invalid input: print "Please try again" and re-prompt
After a set number of failed attempts, exit or use a default name


Store the result as player_name


2. Game Mode Selection

Print "Hello [player_name], are you ready to play Hangman?"
Prompt: "Please select a difficulty: easy or hard"

Validate input — keep asking until they enter "easy" or "hard"
Easy mode: lives = 10
Hard mode: lives = 5




3. The Game
Setup:

Randomly select word from a predefined word list
Create hidden_word — a list of "_" for each letter (e.g. _ _ _ _ _)
Create guessed_letters = [] to track previous guesses
Print "The word has [len(word)] letters"
Print the current hangman graphic (based on lives remaining)

Each Turn:

Display current hidden_word and lives remaining
Ask: "Guess a letter, or if you're feeling confident, guess the whole word"
Player chooses one input type per turn:

Letter guess — disables word guess for that turn
Word guess — disables letter guess for that turn



If guessing a letter:

Check if letter was already in guessed_letters

If yes: "You already guessed that — no life deducted"
If no: add to guessed_letters

If letter is in word: reveal all its positions in hidden_word, print "Good guess!"
If letter is not in word: lives -= 1, print "Wrong! [lives] lives remaining", update hangman graphic




Check if hidden_word is fully revealed → player wins

If guessing the whole word:

If guess == word:

Print "You guessed it! The condemned man did not hang! You win! 🎉"
If you enjoyed the game, please play again :)"`


If guess != word:

lives -= 1, print "Wrong word! [lives] lives remaining"



When lives == 0:

Break out of the game loop
Print the completed hangman graphic
Print "You lose — unlucky. Try harder next time!"
Reveal the correct word: "The word was: [word]"


4. Play Again

After a win or loss, return to game mode selection (game_mode)
Ask "Would you like to play again? (yes/no)"

If yes → restart from step 2 (keep the same player name)
If no → print a goodbye message and exit
"""

##naming element of the game
def askname():
  while True:
    player_name = input("The executioner invites you to provide your name:")
    if(player_name.isalpha()):
      print("The executioner says: 'A fine name indeed,", player_name, ". Welcome, let's play hangman.'")
      return player_name
    else:
      print("The executioner says: '", player_name, "HA! That is a quite ridiculous name. Please try again with letters, for I hate spaces and numbers |:<'")

def gamecommence():
  print("If you want to free the condemned man, then you must guess the word I'm thinking of!")
  guess = input("I'll give you 6 chances, and some hints along the way. Would you like to guess a letter or a word?")
    if(guess == 'letter'):
      input("put letter here:")
    if(guess == 'word'):
      input("put word here:")

##secret word coding

word_or_letter = input("Please enter whether you would like to guess a word, or a letter...")lower()##lowercase input
if word_or_letter == 'word'
  #def word_guess
if word_or_letter == 'letter'
  #def letter_guess

    lives = 6
    wrong_guess = 0


    while incorrect_guess < lives:

      execution_word = 'Python'
      word_letters = list(execution_word)
      guessed_letters = []


        for letter in word_letters:
          if letter in guessed_letters:
            show.append(letter)
          else:
            show.append("_")
            and lives-=1

        print(" "join.(show))

      if "_" not in show:
        print("Congratulations! You chose wisely...the hangman was never hanged, and is a freeman once more.")
        break

##this is used like a counter. It takes C and adds 1 to it. Good for loops
##if i were to do WHEN c+=1<6 THEN, the game continues whilst condition is TRUE. WHEN it is FALSE, the loop breaks, and losing message is returned
chances=0
lives = 6
while lives - chances > 0: #is true, then game continues
  if guessed_letter not in secret word
    then chances+=1

def guess_letter(guessed_letters, word_letters, wrong_guess, lives, execution_word):
    letter = input("The word I'm thinking of is", len(execution_word), "letters long. Which letter will you choose?").lower()
      if len(letter) !=1
        break
      print("CHEATER! Only one letter at a time, be careful or I might dock one of your lives.")

    if letter in guessed_letters:
        print("You have already guessed that letter, try again.")
    elif letter in word_letters:
        guessed_letters.append(letter)
        print("Hm, yes. I'll allow it. That letter is in the word, after all.")
    else:
        wrong_guess += 1
        print("AHA! A rookie error. That letter is not in the word. You have", int(lives - wrong_guess), "lives remaining.")

    return wrong_guess


def guess_word(execution_word, wrong_guess, lives):
    word = input("Enter your word: ").lower()

    if word == execution_word.lower():
        print("Congratulations! You chose wisely...the hangman was never hanged, and is a freeman once more.")
        return True
    else:
        wrong_guess += 1
        print("no, no, no, no, NO! WRONG! Be careful, you only have", int(lives - wrong_guess), "lives remaining.")
        return False